#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Convenience wrapper for running onionrouter directly from source tree."""
from onionrouter.rerouter import main


if __name__ == '__main__':
    main()
